---
abstract: 'import data from Parltrack into Catmandu'
author:
  - 'Jonas Smedegaard (JONASS) <dr@jones.dk>'
build_requires:
  Test::Compile: '0'
  Test::Fixme: '0'
  Test::More: '0.61'
  Test::Pod: '1.00'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.023, CPAN::Meta::Converter version 2.142690'
keywords:
  - 'Big Data'
  - Content
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-Importer-Parltrack
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Catmandu::Importer::Parltrack:
    file: lib/Catmandu/Importer/Parltrack.pm
    version: '0.001'
requires:
  Catmandu::Importer::getJSON: '0'
  Catmandu::Sane: '0'
  Moo: '1.000000'
  Types::Standard: '0'
  URI::Template: '0'
  perl: '5.010001'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/Catmandu-Importer-Parltrack/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Catmandu-Importer-Parltrack
  homepage: https://metacpan.org/release/Catmandu-Importer-Parltrack
  license: http://dev.perl.org/licenses/
  repository: https://anonscm.debian.org/cgit/parl/Catmandu-Importer-Parltrack.git
version: '0.001'
x_help_wanted:
  - tester
  - documenter
